DROP TABLE CHATROOM;
DROP TABLE MESSAGE;

DROP SEQUENCE MESSAGE_ID;
DROP SEQUENCE CHATROOM_ID;

CREATE SEQUENCE MESSAGE_ID;
CREATE SEQUENCE CHATROOM_ID;

CREATE TABLE CHATROOM ( 
   CHATROOM_ID NUMBER PRIMARY KEY,
   CHATROOM_BUYER VARCHAR2(100) NOT NULL,
   CHATROOM_SELLER VARCHAR2(100) NOT NULL,
   CHATROOM_TITLE VARCHAR2(100) NOT NULL,
   CHATROOM_REGDATE DATE NOT NULL,
   CONSTRAINT FK_CHATROOM_BUYER FOREIGN KEY(CHATROOM_BUYER) REFERENCES USERS (USERID)
);

CREATE TABLE MESSAGE (
   MESSAGE_ID NUMBER PRIMARY KEY,
   MESSAGE_SENDER VARCHAR2(45) NOT NULL,
   MESSAGE_RECEIVER VARCHAR2(45) NOT NULL,
   MESSAGE_CONTENT VARCHAR2(4000) NOT NULL,
   MESSAGE_REGDATE DATE NOT NULL,
   CHATROOM_ID NUMBER,
   CONSTRAINT FK_CHATROOM_ID FOREIGN KEY(CHATROOM_ID) REFERENCES CHATROOM (CHATROOM_ID)
);



SELECT * FROM CHATROOM;
